import './globals.css'

import type { Metadata } from 'next'
import { Carattere, Roboto } from 'next/font/google'

const carratte = Carattere({
  subsets: ['latin'],
  variable: '--font-carattere',
  weight: '400'
})

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${carratte.variable} ${roboto.variable}`}>{children}</body>
    </html>
  )
}
